# Compiler and flags
CC     := gcc
CFLAGS := -Wall -Wextra -MMD -MP -g -lX11 -lXrandr
TARGET := runmenu

# Automatically discover all .c files in the current directory
SRCS   := $(wildcard *.c)
OBJS   := $(SRCS:.c=.o)
DEPS   := $(OBJS:.o=.d)

# Default target (runs when you type 'make')
all: $(TARGET)

# Link object files into the final executable
$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $^ -o $@

# Compile .c files into .o object files
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Clean up generated build artifacts
clean:
	rm -f $(TARGET) $(OBJS) $(DEPS)

install: $(TARGET)
	sudo cp $(TARGET) /bin/

# Automatically include header dependency rules generated by compiler
-include $(DEPS)

.PHONY: all clean